name: Screenshot machine

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build Dockerfile 
      run: docker build . --file lib/Dockerfile --tag screen-tardis:$(date +%s)
