name: Screenshot machine

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Dockerfile 
      run: docker build . --file lib/Dockerfile --tag screen-tardis:$(date +%s)
    - name: Run container
      run: docker run screen-tardis && docker cp screen-tardis:github.png gh.png
