name: 📷 Paparazzi

on: push


env:
  CI: true
  FORCE_COLOR: 1

jobs:
  step:
    name: Take screenshots
    runs-on: ubuntu-latest
    container: mamuso/fluxcapacitor:latest
    steps:
      - name: Get current time
        uses: srfrnk/current-time@master
        id: current-time
        with:
          format: YYYY-MM-DD
        run: echo $TIME
    env:
      TIME: ${{ steps.current-time.outputs.time }}
      POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
      AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
      SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
      FLUX_LOGIN: ${{ secrets.FLUX_LOGIN }}
      FLUX_PASSWORD: ${{ secrets.FLUX_PASSWORD }}
      FLUX_COOKIE: ${{ secrets.FLUX_COOKIE }}
      FLUX_DOMAIN: ${{ secrets.FLUX_DOMAIN }}
