name: 📷 Paparazzi

on:
  schedule:
    - cron: 0 0 */3 * *

env:
  CI: true
  FORCE_COLOR: 1

jobs:
  step:
    name: Take screenshots
    runs-on: ubuntu-latest
    container: mamuso/fluxcapacitor:latest
    steps:
      - name: Set current time
        uses: srfrnk/current-time@master
        id: current-time
        with:
          format: YYYY-MM-DD
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Node
        uses: actions/setup-node@v1
        with:
          node-version: "13.x"
      - name: Yarn
        run: npm install -g yarn
      - name: Dependencies
        run: yarn install --production
      - name: Prisma
        run: yarn workspace api run prisma2 generate
      - name: Set up
        run: yarn workspace paparazzi setup --production
        env:
          TIME: ${{ steps.current-time.outputs.formattedTime }}
      - name: Download
        run: yarn workspace paparazzi getcurrent --production
        env:
          TIME: ${{ steps.current-time.outputs.formattedTime }}
      - name: Capture
        run: yarn workspace paparazzi capture --production
        env:
          TIME: ${{ steps.current-time.outputs.formattedTime }}
      - name: Resize
        run: yarn workspace paparazzi resize --production
        env:
          TIME: ${{ steps.current-time.outputs.formattedTime }}
      - name: Compare
        run: yarn workspace paparazzi compare --production
        env:
          TIME: ${{ steps.current-time.outputs.formattedTime }}
      - name: Sparklines
        run: yarn workspace paparazzi sparklines --production
        env:
          TIME: ${{ steps.current-time.outputs.formattedTime }}
      - name: Cleanup
        run: yarn workspace paparazzi setcurrent --production
        env:
          TIME: ${{ steps.current-time.outputs.formattedTime }}
    env:
      POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
      AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
      SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
      FLUX_LOGIN: ${{ secrets.FLUX_LOGIN }}
      FLUX_PASSWORD: ${{ secrets.FLUX_PASSWORD }}
      FLUX_COOKIE: ${{ secrets.FLUX_COOKIE }}
      FLUX_DOMAIN: ${{ secrets.FLUX_DOMAIN }}
