name: 📷 Paparazzi

on: [push]

env:
  CI: true
  FORCE_COLOR: 1

jobs:
  step:
    name: Take screenshots
    runs-on: ubuntu-latest
    container: mamuso/fluxcapacitor:latest
    steps:
      - uses: actions/checkout@v2
      - run: "cd .github/workflows/paparazzi && npm install && node playground.js"
    env:
      AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
