name: 📷 Paparazzi
on:
  schedule:
    - cron: 0 0 */3 * *

env:
  CI: true
  FORCE_COLOR: 1

jobs:
  step:
    name: Take screenshots
    runs-on: ubuntu-latest
    container: mamuso/fluxcapacitor:latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "13.x"
      - run: npm install -g yarn
      - run: yarn install --production
      - run: yarn workspace api run prisma2 generate
      - run: yarn run paparazzi --unhandled-rejections=strict --production
    env:
      POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
      AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
